# Generated by Django 3.1.13 on 2021-07-27 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.CharField(default='Description', max_length=50),
        ),
    ]
